fixed nonce issue and basestring variable
GovTechSG/csharp-apex-api-security pull request #1
Opened 2018-09-10 08:29 UTC by punjabisingh

# Description

Fixed the bug on nonce variable to return base64string from long and fixed the issue for basestring to have null variable. 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Run Unit Test Cases.

2018-09-11 10:48 UTC, robincher requested changes
Require some minor updates and it will be good to go

2018-09-11 10:48 UTC, robincher commented on ApiUtilLib/ApiAuthorization.cs
> +                //nonce = BitConverter.ToInt64(data, 0);
Can removed unused code

2018-09-11 10:48 UTC, robincher commented on CHANGELOG.md
> ++ 2018-09-10 - Bug fixes.
Can be more precise on the changes, like what is done to enhance the library to handle query params.

2018-09-13 02:24 UTC, closed without merging

2018-09-13 02:25 UTC, punjabisingh commented
updated bug fixes