Development
GovTechSG/csharp-apex-api-security pull request #9
Opened 2018-12-13 06:33 UTC by punjabisingh

# Description

Fixed issue with failed test case, created folder and description to download test data and certificates for test cases.

Fixes # 6

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

All test cases passes locally.

2018-12-13 08:39 UTC, kelvinwijaya requested changes
Remove the .vs and .idea folder
Also keep the packages.config data as current version as it broke the Travis CI mono framework (refer to the Travis CI Build result: https://travis-ci.org/GovTechSG/csharp-apex-api-security/builds/467362431?utm_source=github_status&utm_medium=notification)

Also for the pulling the test data, the program has done auto download, no need to ask user to specifically download the test files from the repo

2018-12-13 09:05 UTC, kelvinwijaya commented
Also the TestData/* don't commit
Reason using the GetLocalPath is the testdata will only be generated during Build phase. It will be inside bin/Release folder

2018-12-16 03:47 UTC, robincher commented
The test built is still failing in the CI, please do not merge it yet.

2019-01-01 10:38 UTC, robincher requested changes

2019-01-01 10:38 UTC, robincher commented on .vs/ApiSecuritySolution/xs/UserPrefs.xml
> +      <File FileName="ApiUtilLibTest/Certificates/cert/alpha/ReadMe.txt" Line="1" Column="1" />
What is the purpose for this Readme? It can be included in the main README.md

2019-01-01 10:38 UTC, robincher commented on ApiUtilLibTest/Certificates/cert/alpha/ReadMe.txt
> +﻿Download Latest Test Case / CErtificates from below URL and update testDataPath accordingly or copy into TestData folder inside project.
Move this information to main README.md.

2019-01-18 06:24 UTC, closed without merging